### ISSUE TITLE
Enhancing the ui

### ISSUE THREAD

**Issue by suyalamritanshu** [suyalamritanshu/Images-App#3]

**Comment by SiddyDevelops** [comment]
I would like to work on this issue. Can you please assign it to me ?

**Comment by suyalamritanshu** [comment]
sure, issue is yours

**Comment by SiddyDevelops** [comment]
@suyalamritanshu Sir, I have generated a PR #6. Please review it. Also please add ```hactober-accepted``` label to my PR if you like it. Thank You.
