### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by SiddyDevelops** [suyalamritanshu/Images-App#8]
Sir I would like to add an attractive splash screen to this app. Can you please assign this to me?

**Comment by suyalamritanshu** [comment]
yes sure

**Comment by SiddyDevelops** [comment]
Can you please add hactoberfest label.

**Comment by SiddyDevelops** [comment]
@suyalamritanshu  Sir I have generated a PR #9. Please review it. Also please add ```hactoberfest``` labels to this issue. Thank You.
